package privatetypes

// Code generated by "go run types_generate.go"; DO NOT EDIT.

import (
	"testing"

	dnsv2 "codeberg.org/miekg/dns"
)

func TestBunnyDnsScript(t *testing.T) {
	y := &BUNNYDNSSCRIPT{
		Hdr:  dnsv2.Header{Name: "example.org.", Class: dnsv2.ClassINET},
		Code: "export default { async fetch() {} };",
	}
	rry, err := dnsv2.New(y.String())
	if err != nil {
		t.Fatal(err)
	}
	if rry.String() != y.String() {
		t.Fatalf("BUNNY_DNS_SCRIPT string presentations should be identical:\n%s\n%s", rry.String(), y.String())
	}
}

// Code generated by "go run types_generate.go"; DO NOT EDIT.
