package privatetypes

// Code generated by "go run types_generate.go"; DO NOT EDIT.

import (
	"fmt"
	"strconv"

	dnsv2 "codeberg.org/miekg/dns"
	dnsutilv2 "codeberg.org/miekg/dns/dnsutil"
	"github.com/DNSControl/dnscontrol/v5/pkg/mustbe"
	privatetypesrdata "github.com/DNSControl/dnscontrol/v5/pkg/privatetypes/rdata"
)

// BUNNY_DNS_SCRIPT

func init() {
	Register(TypeBUNNYDNSSCRIPT, "BUNNY_DNS_SCRIPT", func() dnsv2.RR { return new(BUNNYDNSSCRIPT) }, privatetypesrdata.MakeBUNNYDNSSCRIPT)
}

const TypeBUNNYDNSSCRIPT = uint16(65323)

type BUNNYDNSSCRIPT struct {
	Hdr dnsv2.Header

	privatetypesrdata.BUNNYDNSSCRIPT
	// Code                 string
}

// Typer interface.

func (rr *BUNNYDNSSCRIPT) Type() uint16 { return TypeBUNNYDNSSCRIPT }

// RR interface.

func (rr *BUNNYDNSSCRIPT) Header() *dnsv2.Header { return &rr.Hdr }
func (rr *BUNNYDNSSCRIPT) Len() int {
	return rr.Hdr.Len() + rr.Data().Len()
}
func (rr *BUNNYDNSSCRIPT) Data() dnsv2.RDATA {
	return privatetypesrdata.BUNNYDNSSCRIPT{Code: rr.Code}
}
func (rr *BUNNYDNSSCRIPT) Clone() dnsv2.RR {
	return &BUNNYDNSSCRIPT{
		Hdr:  rr.Hdr,
		Code: rr.Code}
}
func (rr *BUNNYDNSSCRIPT) String() string {
	return (rr.Header().Name + "\t" +
		strconv.FormatInt(int64(rr.Header().TTL), 10) + "\t" +
		dnsutilv2.ClassToString(rr.Header().Class) + "\tBUNNY_DNS_SCRIPT\t" + rr.Data().String())
}

// Parse makes an RDATA for this type using the tokens from dnsv2's parser.
func (rr *BUNNYDNSSCRIPT) Parse(tokens []string, s string) error {
	args := TokensToArgs(tokens)
	if len(args) != 1 {
		return fmt.Errorf("BUNNY_DNS_SCRIPT requires exactly 1 arguments, got %d: %v", len(args), args)
	}
	rr.Code = mustbe.RawString(args[0])
	return nil
}

// Code generated by "go run types_generate.go"; DO NOT EDIT.
