// generated by get-zones. This is 'a decent first draft' and requires editing.

var DSP_BIND = NewDnsProvider("bind", "BIND");
var REG_CHANGEME = NewRegistrar("none");

D("ds.com", REG_CHANGEME,
	{no_ns: "true"},
	DnsProvider(DSP_BIND),
	//SOA("@", "ns3.serverfault.com.", "sysadmin.stackoverflow.com.", 3600, 600, 604800, 1440),
	DS("geo", 14480, 13, 2, "bb1c4b615cded2b34347cf23710471934d972f1e34f53b54ed8d5f786202c73b"),
);

