package privatetypesrdata

// Code generated by "go run types_generate.go"; DO NOT EDIT.

import (
	"fmt"
	"strings"

	dnsv2 "codeberg.org/miekg/dns"
	"github.com/DNSControl/dnscontrol/v5/pkg/mustbe"
	"github.com/DNSControl/dnscontrol/v5/pkg/nrc"
	"github.com/DNSControl/dnscontrol/v5/pkg/txtutil"
)

type R53ALIAS struct {
	AliasType        string
	Target           string `dnscontrol:"targethost"`
	EvalTargetHealth string
	ZoneID           string
}

func (rd R53ALIAS) Len() int {
	return len(rd.String())
}

func (rd R53ALIAS) String() string {
	parts := make([]string, 0, 4)
	parts = append(parts, txtutil.ZoneifyString(rd.AliasType))
	parts = append(parts, rd.Target)
	parts = append(parts, txtutil.ZoneifyString(rd.EvalTargetHealth))
	parts = append(parts, txtutil.ZoneifyString(rd.ZoneID))
	return strings.Join(parts, " ")
}

func MakeR53ALIAS(origin string, _ map[string]string, isEnabled nrc.Flags, args ...any) (dnsv2.RDATA, error) {
	mustbe.ValidArgs(args)
	if len(args) < 2 || len(args) > 4 {
		return nil, fmt.Errorf("R53_ALIAS expects 4 arguments, got %d: %+v", len(args), args)
	}
	for len(args) < 4 {
		args = append(args, "")
	}
	if isEnabled.TargetIsFqdnNoDot {
		origin = "."
	}
	targetHost1, err := mustbe.TargetHost(origin, isEnabled, args[1])
	if err != nil {
		return nil, err
	}
	return R53ALIAS{
		AliasType:        mustbe.RawString(args[0]),
		Target:           targetHost1,
		EvalTargetHealth: mustbe.RawString(args[2]),
		ZoneID:           mustbe.RawString(args[3]),
	}, nil
}

// Code generated by "go run types_generate.go"; DO NOT EDIT.
