package privatetypesrdata

// Code generated by "go run types_generate.go"; DO NOT EDIT.

import (
	"fmt"
	"strings"

	dnsv2 "codeberg.org/miekg/dns"
	"github.com/DNSControl/dnscontrol/v5/pkg/mustbe"
	"github.com/DNSControl/dnscontrol/v5/pkg/nrc"
	"github.com/DNSControl/dnscontrol/v5/pkg/txtutil"
)

type AKAMAITLC struct {
	AnswerType string
	Target     string `dnscontrol:"targethost"`
}

func (rd AKAMAITLC) Len() int {
	return len(rd.String())
}

func (rd AKAMAITLC) String() string {
	parts := make([]string, 0, 2)
	parts = append(parts, txtutil.ZoneifyString(rd.AnswerType))
	parts = append(parts, rd.Target)
	return strings.Join(parts, " ")
}

func MakeAKAMAITLC(origin string, _ map[string]string, isEnabled nrc.Flags, args ...any) (dnsv2.RDATA, error) {
	mustbe.ValidArgs(args)
	if len(args) != 2 {
		return nil, fmt.Errorf("AKAMAITLC expects 2 arguments, got %d: %+v", len(args), args)
	}
	if isEnabled.TargetIsFqdnNoDot {
		origin = "."
	}
	targetHost1, err := mustbe.TargetHost(origin, isEnabled, args[1])
	if err != nil {
		return nil, err
	}
	return AKAMAITLC{
		AnswerType: mustbe.RawString(args[0]),
		Target:     targetHost1,
	}, nil
}

// Code generated by "go run types_generate.go"; DO NOT EDIT.
