package privatetypesrdata

// Code generated by "go run types_generate.go"; DO NOT EDIT.

import (
	"fmt"
	"strings"

	dnsv2 "codeberg.org/miekg/dns"
	"github.com/DNSControl/dnscontrol/v5/pkg/mustbe"
	"github.com/DNSControl/dnscontrol/v5/pkg/nrc"
)

type AKAMAICDN struct {
	Target string `dnscontrol:"targethost"`
}

func (rd AKAMAICDN) Len() int {
	return len(rd.String())
}

func (rd AKAMAICDN) String() string {
	parts := make([]string, 0, 1)
	parts = append(parts, rd.Target)
	return strings.Join(parts, " ")
}

func MakeAKAMAICDN(origin string, _ map[string]string, isEnabled nrc.Flags, args ...any) (dnsv2.RDATA, error) {
	mustbe.ValidArgs(args)
	if len(args) != 1 {
		return nil, fmt.Errorf("AKAMAICDN expects 1 arguments, got %d: %+v", len(args), args)
	}
	if isEnabled.TargetIsFqdnNoDot {
		origin = "."
	}
	targetHost0, err := mustbe.TargetHost(origin, isEnabled, args[0])
	if err != nil {
		return nil, err
	}
	return AKAMAICDN{
		Target: targetHost0,
	}, nil
}

// Code generated by "go run types_generate.go"; DO NOT EDIT.
